[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "social-trend-analyzer-api"

[services.variables]
# 这些环境变量将在 Railway 控制台中设置
# ZHIPU_API_KEY = "your_zhipu_api_key"
# TWITTERAPI_IO_KEY = "your_twitter_api_key"
# DATABASE_URL = "sqlite:///./app.db"